//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Resumes;
using HirefyAI.Domain.Entities;
using HirefyAI.Application.DataTransferObjects.Resumes;

namespace Services.Resumes
{
    public interface IResumesService
    {
        Task<ResumeViewModel> AddAsync(ResumeCreationDto resumeCreationDto);
        Task<List<ResumeViewModel>> GetAllAsync();
        Task<ListResult<ResumeViewModel>> FilterAsync(PaginationOptions filter);
        Task<ResumeDetailedViewModel> GetByIdAsync(int id);
        Task<ResumeViewModel> UpdateAsync(int id, ResumeModificationDto resumeModificationDto);
        Task<ResumeViewModel> DeleteAsync(int id);
    }
}