//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Books;
using HirefyAI.Domain.Entities;

namespace Services.Books
{
    public interface IBooksService
    {
        Task<BookViewModel> AddAsync(BookCreationDto bookCreationDto);
        Task<List<BookViewModel>> GetAllAsync();
        Task<ListResult<BookViewModel>> FilterAsync(PaginationOptions filter);
        Task<BookViewModel> GetByIdAsync(long id);
        Task<BookViewModel> UpdateAsync(long id, BookModificationDto bookModificationDto);
        Task<BookViewModel> DeleteAsync(long id);
    }
}