//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using Services.Resumes;
using Common.Paginations.Models;
using Common;
using DataTransferObjects.Resumes;
using HirefyAI.Domain.Entities;
using Microsoft.AspNetCore.Authorization;

namespace Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize]
    public class ResumesController : ControllerBase
    {
        private readonly IResumesService _resumesService;
        public ResumesController(IResumesService resumesService)
        {
            _resumesService = resumesService;
        }

        [HttpPost]
        public async Task<Result<ResumeViewModel>> AddAsync(ResumeCreationDto resumeCreationDto)
        {
            return Result<ResumeViewModel>.Success(await _resumesService.AddAsync(resumeCreationDto));
        }

        [HttpGet]
        public async Task<Result<List<ResumeViewModel>>> GetAllAsync()
        {
            return Result<List<ResumeViewModel>>.Success(await _resumesService.GetAllAsync());
        }

        [HttpPost("filter")]
        public async Task<Result<ListResult<ResumeViewModel>>> FilterAsync(PaginationOptions filter)
        {
            return Result<ListResult<ResumeViewModel>>.Success(await _resumesService.FilterAsync(filter));
        }

        [HttpGet("{id}")]
        public async Task<Result<ResumeViewModel>> GetByIdAsync(int id)
        {
            return Result<ResumeViewModel>.Success(await _resumesService.GetByIdAsync(id));
        }

        [HttpPut("{id}")]
        public async Task<Result<ResumeViewModel>> UpdateAsync(int id, ResumeModificationDto resumeModificationDto)
        {
            return Result<ResumeViewModel>.Success(await _resumesService.UpdateAsync(id, resumeModificationDto));
        }

        [HttpDelete("{id}")]
        public async Task<Result<ResumeViewModel>> DeleteAsync(int id)
        {
            return Result<ResumeViewModel>.Success(await _resumesService.DeleteAsync(id));
        }
    }
}