//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;

namespace DataTransferObjects.Users;

public class UserCreationDto
{
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public string Email { get; set; }
}
