//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Books;

public class BookViewModel
{
    public string Name { get; set; }
    public string Author { get; set; }
    public BookType Type { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? Created { get; set; }
    public string LastModifiedBy { get; set; }
    public DateTime? LastModified { get; set; }
    public long Id { get; set; }
}
