//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Skills;

public class SkillCreationDto
{
	public string Name { get; set; }
	public string Description { get; set; }
}
