//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Educations;

public class EducationCreationDto
{
	public string Degree { get; set; }
	public string Institution { get; set; }
	public DateTime StartDate { get; set; }
	public DateTime? EndDate { get; set; }
	public string Description { get; set; }
	public int ResumeId { get; set; }
}
