//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Educations;

public class EducationModificationDto
{
	public string Degree { get; set; }
	public string Institution { get; set; }
    public DateOnly StartDate { get; set; }
    public DateOnly? EndDate { get; set; }
	public string Description { get; set; }
}
