//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using DataTransferObjects.Educations;
using DataTransferObjects.Experiences;

namespace DataTransferObjects.Resumes;

public class ResumeCreationDto
{
	public string Name { get; set; }

	public string FirstName { get; set; }
    public string LastName { get; set; }
    public string JobTitle { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Summary { get; set; }

    public List<string> Skills { get; set; } = new List<string>();
    public List<EducationCreationDto> Educations { get; set; } = new List<EducationCreationDto>();
    public List<ExperienceCreationDto> Experiences { get; set; } = new List<ExperienceCreationDto>();

	public int TemplateId { get; set; }
}
