//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using DataTransferObjects.Educations;
using DataTransferObjects.Experiences;

namespace DataTransferObjects.Resumes;

public class ResumeModificationDto
{
	public string Name { get; set; }

	public string FirstName { get; set; }
    public string LastName { get; set; }
    public string JobTitle { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string Summary { get; set; }

    public List<string> Skills { get; set; } = new List<string>();
    public List<EducationModificationDto> Educations { get; set; } = new List<EducationModificationDto>();
    public List<ExperienceModificationDto> Experiences { get; set; } = new List<ExperienceModificationDto>();
}
