//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Resumes;

public class ResumeCreationDto
{
	public string Name { get; set; }
	public int TemplateId { get; set; }
}
