//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Resumes;

public class ResumeCreationDto
{
	public string Name { get; set; }

	public string FirstName { get; set; }
    public string LastName { get; set; }
    public string JobTitle { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }

	public int TemplateId { get; set; }
}
