//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Educations;
using HirefyAI.Domain.Entities;

namespace Services.Educations
{
    public interface IEducationsService
    {
        Task<EducationViewModel> AddAsync(EducationCreationDto educationCreationDto);
        Task<List<EducationViewModel>> GetAllAsync();
        Task<ListResult<EducationViewModel>> FilterAsync(PaginationOptions filter);
        Task<EducationViewModel> GetByIdAsync(long id);
        Task<EducationViewModel> UpdateAsync(long id, EducationModificationDto educationModificationDto);
        Task<EducationViewModel> DeleteAsync(long id);
    }
}