//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Skills;
using HirefyAI.Domain.Entities;

namespace Services.Skills
{
    public interface ISkillsService
    {
        Task<SkillViewModel> AddAsync(SkillCreationDto skillCreationDto);
        Task<List<SkillViewModel>> GetAllAsync();
        Task<ListResult<SkillViewModel>> FilterAsync(PaginationOptions filter);
        Task<SkillViewModel> GetByIdAsync(int id);
        Task<SkillViewModel> UpdateAsync(int id, SkillModificationDto skillModificationDto);
        Task<SkillViewModel> DeleteAsync(int id);
    }
}