//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Experiences;
using HirefyAI.Domain.Entities;

namespace Services.Experiences
{
    public interface IExperiencesService
    {
        Task<ExperienceViewModel> AddAsync(ExperienceCreationDto experienceCreationDto);
        Task<List<ExperienceViewModel>> GetAllAsync();
        Task<ListResult<ExperienceViewModel>> FilterAsync(PaginationOptions filter);
        Task<ExperienceViewModel> GetByIdAsync(int id);
        Task<ExperienceViewModel> UpdateAsync(int id, ExperienceModificationDto experienceModificationDto);
        Task<ExperienceViewModel> DeleteAsync(int id);
    }
}