//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Experiences;

public class ExperienceCreationDto
{
	public string JobTitle { get; set; }
	public string CompanyName { get; set; }
	public DateTime StartDate { get; set; }
	public DateTime? EndDate { get; set; }
	public string Description { get; set; }
	public int ResumeId { get; set; }
}
