//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using HirefyAI.Domain.Entities;

namespace DataTransferObjects.Experiences;

public class ExperienceModificationDto
{
	public string JobTitle { get; set; }
	public string CompanyName { get; set; }
	public DateTime StartDate { get; set; }
	public bool IsCurrent { get; set; } = false;
	public DateTime? EndDate { get; set; }
	public string Summary { get; set; }
}
