name: Dockerize and Deploy Hirefy Back

on:
  push:
    branches:
      - 'master'
env:
  IMAGE_TAG: ${{ github.ref_name == 'master' && 'latest'   }}     
  CONTAINER_NAME: ${{ github.ref_name == 'master' && 'hirefy-api' }}
  FOLDER: ${{ github.ref_name == 'master' && '~/fond' }}
  HOST: ${{ github.ref_name == 'master' && secrets.DEV_SSH_HOST  }}
  USER: ${{ github.ref_name == 'master' && secrets.DEV_SSH_USER  }}
  PASSWORD: ${{ github.ref_name == 'master' && secrets.DEV_SSH_PASSWORD  }}
  PORT: ${{ github.ref_name == 'master' && secrets.DEV_SSH_PORT  }}

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push merchant 
        uses: docker/build-push-action@v2
        with:
          file: src/HirefyAI.Api/Dockerfile
          push: true
          tags: taqsim/${{env.CONTAINER_NAME}}:${{ env.IMAGE_TAG }}
          no-cache: true 
        
  deploy:    
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: executing remote ssh commands using keys
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 20m
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASSWORD }}
          port: ${{ env.PORT }}
          script: |
            echo "Pulling latest docker image and restarting backend app.."
            cd ${{ env.FOLDER }}
            docker pull taqsim/${{env.CONTAINER_NAME}}:${{ env.IMAGE_TAG }} && docker rm -f ${{env.CONTAINER_NAME}} && docker-compose up -d ${{env.CONTAINER_NAME}} 
