//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Templates;
using HirefyAI.Domain.Entities;

namespace Services.Templates
{
    public interface ITemplatesService
    {
        Task<TemplateViewModel> AddAsync(TemplateCreationDto templateCreationDto);
        Task<List<TemplateViewModel>> GetAllAsync();
        Task<ListResult<TemplateViewModel>> FilterAsync(PaginationOptions filter);
        Task<TemplateViewModel> GetByIdAsync(int id);
        Task<TemplateViewModel> UpdateAsync(int id, TemplateModificationDto templateModificationDto);
        Task<TemplateViewModel> DeleteAsync(int id);
    }
}